### ISSUE TITLE
Using CODEOWNERS file for automatic notifications

### ISSUE THREAD

**Issue by ALABSTM** [ALABSTM/STM32CubeXX#1]
**Expected behavior**
Normally e-mail notifications shall be sent to members ASELSTM and MBENSTM once this issue created.

**Requested**
@ASELSTM and @MBENSTM, please answer this issue to acknowledge you have been notified of its creation.

With regards

**Comment by ALABSTM** [comment]
Expected behavior
Normally e-mail notifications shall be sent to members ASELSTM and MBENSTM once this issue created.

Requested
@ASELSTM and @MBENSTM, please answer this issue to acknowledge you have been notified of its creation.

**Link to the issue**
https://github.com/ALABSTM/STM32CubeXX/issues/1

With regards

**Comment by ALABSTM** [comment]
Still waiting for answer...

**Comment by ASELSTM** [comment]
This is my answer

**Comment by ALABSTM** [comment]
Good! An answer finally!
